### ISSUE TITLE
R2SDF - Butterfly is overflowing

### ISSUE THREAD

**Issue by mschiller-nrao** [talonmyburgh/casper_dspdevel#38]
Something seems off with the butterfly using add/sub
The R2SDF testbench is overflowing.

**Comment by talonmyburgh** [comment]
I don't quite understand why but it seems that the ADDSUB_MACRO is correctly detecting overflow. Since we are looking at the carryout flag as the overflow this might be inaccurate:
![image](https://github.com/talonmyburgh/casper_dspdevel/assets/28049678/cf896ce6-eb63-4743-831e-03a2e98ed501)

**Comment by talonmyburgh** [comment]
The above is for a latency of one in the DSP ADDSUB. Our data has a dynamic range of 2^18 usually ->  -1131072 : 131071.
Looking at the first few examples:
-507+(-15939) = -16446 : don't expect overflow/carry but addition_overflow is high
-507-(-15939) = 15432 : don't expect overflow/carry but subtraction_overflow is high.

This may be detecting sign flips as overflow which is correct. Looking at the binary representation backs this up:
![image](https://github.com/talonmyburgh/casper_dspdevel/assets/28049678/3bde2c3e-f336-488d-af23-2db80e5b3170)

**Comment by talonmyburgh** [comment]
@mschiller-nrao please review new overflow detection method in 038f20de36196187c284cb7a6a01c44d49c75545

Still see overflow being raised on occasion.

**Comment by talonmyburgh** [comment]
Note that the `ADD_SVEC` and `SUB_SVEC` increase the bitwidth of the first slv before addition as you mentioned

**Comment by mschiller-nrao** [comment]
This will be fixed with a checkin planned soon
