### ISSUE TITLE
Sync/valid interface adaption breaks inplace-reorder tests

### ISSUE THREAD

**Issue by talonmyburgh** [talonmyburgh/casper_dspdevel#39]
Not sure why this happened, but the inplace-reorder tests on `talon_sync_test` branch now fail. This is likely due to the testbench needing to be adapted to ignore out_val when accompanied by a high out_sync.

Will address in the coming days.

To reproduce, run `tb_tb_fft_r2_pipe/u_rnd_two_real_noise_ip` test.

**Comment by mschiller-nrao** [comment]
This will be fixed with a checkin that I will be pushing soon

**Comment by talonmyburgh** [comment]
Amazing!
