### ISSUE TITLE
Expect additional out_val to accompany last data sample

### ISSUE THREAD

**Issue by talonmyburgh** [talonmyburgh/casper_dspdevel#40]
It would appear that the last out_val is missing and should accompany the output data.

The effect of this is that for tests with variable in_val, the first sample following an FFT window is incorrect (I think).
![image](https://github.com/talonmyburgh/casper_dspdevel/assets/28049678/5f938e0c-da68-44e0-869b-202c74c80dd4)

To reproduce the above, run tb_tb_fft_r2_pipe/u_rnd_two_real_noise

**Comment by mschiller-nrao** [comment]
This is starting at the "Beginning of time" and is related to sync... Still working on understanding exact root cause.

**Comment by mschiller-nrao** [comment]
This was a pipelining problem with out_val in the reorder block.  Changes will be checked in soon

**Comment by talonmyburgh** [comment]
Excellent thanks!
